version: '2'

services:

  postgres_todolist:
    image: bitnami/postgresql:9.6
    environment:
      - POSTGRESQL_DATABASE=todolist

  web_rest:
    restart: always
    build: ./django-rest-swagger
    links:
      - postgres_todolist
    depends_on:
      - postgres_todolist
    ports:
      - '8000:8000'
    command: bash -c "echo 'Starting the REST Server...' && sleep 30 && python manage.py migrate --noinput && python manage.py loaddata users && python manage.py runserver 0.0.0.0:8000"