version: '3'

services:

  postgres_korek:
    image: bitnami/postgresql:9.6
    environment:
      - POSTGRESQL_DATABASE=korek_db
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  postgres_interface:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    links:
      - postgres_korek:postgres
    ports:
      - "5050:80"

#  redis_cache:
#    container_name: 'redis'
#    image: 'redis:3.2.0'
#    ports:
#      - '127.0.0.1:6379:6379'
#    volumes:
#      - 'redisdata:/data'

  web_rest:
    restart: always
    build: ./django-rest-swagger
    environment:
      # PUBLIC PRIVATE PRIVATE-VALIDATION
      - PRIVACY_MODE=PRIVATE
      - EMAIL_HOST=smtp.yyy.com
      - EMAIL_HOST_USER=xxx.xxx@yyy.com
      - EMAIL_HOST_PASSWORD=changeme
    links:
      - postgres_korek
    depends_on:
      - postgres_korek
    volumes:
      - ./media/:/code/myapp/app/media/

  nginx:
    build: ./nginx
    depends_on:
      - web_rest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/nginx.conf
      - ./media/:/media/:ro
    ports:
      - "80:80"


# SSL Certificate
  rproxy :
    image: eforce21/letsencrypt-nginx-proxy:1.0.2
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      #- ./nginx:/etc/letsencrypt/archive
    #environment:
      #- LETSENCRYPT_EMAIL=<your_email@mydomain.de>
    restart: always  


# Monitoring
  # collectd:
  #   build: ./monitoring/collectd
  #   privileged: true
  #   depends_on:
  #     - nginx
  #   #network_mode: host
  #   volumes:
  #     - /proc:/mnt/proc:ro
  #     - ./monitoring/collectd/collectd.conf:/etc/collectd/collectd.conf

  # influxdb:
  #   image: influxdb:1.0
  #   depends_on:
  #     - collectd
  #   ports:
  #     - "8083:8083"
  #     - "8086:8086"
  #     - "25826:25826/udp"
  #   volumes:
  #     - influxdata:/var/lib/influxdb
  #     - ./monitoring/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
  #     - ./monitoring/influxdb/types.db:/usr/share/collectd/types.db:ro

  # grafana:
  #   image: grafana/grafana:5.3.2
  #   depends_on:
  #     - influxdb
  #   links:
  #     - postgres_korek:postgres
  #     - collectd:collectd
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./monitoring/grafana:/var/lib/grafana


volumes:
  pgdata: {}
  redisdata: {}
  influxdata: {}