version: '3'

services:

  postgres_korek:
    image: bitnami/postgresql:11
    environment:
      - POSTGRESQL_DATABASE=korek_db
      - POSTGRESQL_PASSWORD=postgres
    volumes:
      - pgdata:/bitnami

  redis:
    image: 'bitnami/redis:5.0-debian-9'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data
    command: /run.sh --maxmemory 500mb

  web_socket:
    restart: always
    build: ./django-notifier
    environment:
      - DEBUG=True
    links:
      - postgres_korek
      - redis
    depends_on:
      - postgres_korek
      - redis
      - web_rest
    ports:
      - "8000:8000"

  postgres_interface:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    links:
      - postgres_korek:postgres
    ports:
      - "5050:80"

  web_rest:
    restart: always
    build: ./django-rest-swagger
    environment:
      - DEBUG=True
      # PUBLIC PRIVATE PRIVATE-VALIDATION
      - PRIVACY_MODE=PRIVATE-VALIDATION
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_HOST_USER=xxxx.yyy@gmail.com
      - EMAIL_HOST_PASSWORD=changeme
    links:
      - postgres_korek
    depends_on:
      - postgres_korek
    volumes:
      - ./media/:/code/myapp/app/media/


  nginx:
    build: ./nginx
    depends_on:
      - web_rest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./media/:/media/:ro
      - ssl_cetificate:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"


# Monitoring
  collectd:
    build: ./monitoring/collectd
    privileged: true
    depends_on:
      - nginx
      - influxdb
    #network_mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /proc:/mnt/proc:ro
      - ./monitoring/collectd/collectd.conf:/etc/collectd/collectd.conf
      - 'serverlog:/var/log/nginx/'

  influxdb:
    image: influxdb:1.0
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - influxdata:/var/lib/influxdb
      - ./monitoring/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./monitoring/influxdb/types.db:/usr/share/collectd/types.db:ro

  grafana:
    image: grafana/grafana:5.3.2
    depends_on:
      - influxdb
    links:
      - postgres_korek:postgres
      - collectd:collectd
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana


volumes:
  pgdata: {}
  influxdata: {}
  redis_data: {}
  ssl_cetificate:  {}